services:
  resolver:
    build:
      context: .
      dockerfile: service/resolver/Dockerfile
    environment:
      PG_DSN: postgresql://postgres:postgres@db:5432/astro_reason
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on: [db, kafka]

  ingest:
    build:
      context: .
      dockerfile: service/ingest/Dockerfile
    environment:
      PG_DSN: postgresql://postgres:postgres@db:5432/astro_reason
      MINIO_ENDPOINT: http://minio:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on: [db, minio, kafka]

  astro:
    build:
      context: .
      dockerfile: service/astro/Dockerfile.python
    environment:
      PG_DSN: postgresql://postgres:postgres@db:5432/astro_reason
      SE_EPHE_PATH: /opt/ephe
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on: [db, kafka]
